# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/coderman64/UnrealEngine/Linux_Unreal_Engine_5.3.0
GAMEPROJECTFILE =/home/coderman64/Documents/Unreal Projects/RacingGameTest2/RacingGameTest2.uproject

TARGETS = \
	RacingGameTest2-Linux-DebugGame  \
	RacingGameTest2-Linux-Shipping  \
	RacingGameTest2 \
	RacingGameTest2Editor-Linux-DebugGame  \
	RacingGameTest2Editor-Linux-Shipping  \
	RacingGameTest2Editor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RacingGameTest2Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RacingGameTest2Editor-Linux-Debug


RacingGameTest2-Linux-DebugGame:
	 $(PROJECTBUILD) RacingGameTest2 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RacingGameTest2-Linux-Shipping:
	 $(PROJECTBUILD) RacingGameTest2 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RacingGameTest2:
	 $(PROJECTBUILD) RacingGameTest2 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RacingGameTest2Editor-Linux-DebugGame:
	 $(PROJECTBUILD) RacingGameTest2Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RacingGameTest2Editor-Linux-Shipping:
	 $(PROJECTBUILD) RacingGameTest2Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RacingGameTest2Editor:
	 $(PROJECTBUILD) RacingGameTest2Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
